# Generated by Django 6.0 on 2025-12-09 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maruza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.PositiveIntegerField(unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('variant_a', models.CharField(max_length=200)),
                ('variant_b', models.CharField(max_length=200)),
                ('variant_c', models.CharField(max_length=200)),
                ('variant_d', models.CharField(max_length=200)),
                ('togri_javob', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('maruza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='quiz.maruza')),
            ],
        ),
        migrations.CreateModel(
            name='Javob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanlangan_javob', models.CharField(max_length=1)),
                ('is_togri', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.savol')),
            ],
        ),
    ]
